name: Upload Assets to Cloudflare R2

on:
  push:
    branches: [main]

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Cloudflare Wrangler
        run: npm install -g wrangler

      - name: Check Wrangler Authentication
        run: wrangler whoami

      - name: Upload files to R2
        run: |
          wrangler r2 object put biotope-assets/weflciqaa_tier_0.gltf -f "public/assets/Smoked Fish Raw/weflciqaa_tier_0.gltf"
          wrangler r2 object put biotope-assets/weflciqaa_tier_0.bin -f "public/assets/Smoked Fish Raw/weflciqaa_tier_0.bin"
          wrangler r2 object put biotope-assets/potted-plant-1-scene.gltf -f "public/assets/Potted Plant 1/scene.gltf"
          wrangler r2 object put biotope-assets/potted-plant-1-scene.bin -f "public/assets/Potted Plant 1/scene.bin"
          wrangler r2 object put biotope-assets/knobbed-whelk-scene.gltf -f "public/assets/Knobbed Whelk GLTF/scene.gltf"
          wrangler r2 object put biotope-assets/knobbed-whelk-scene.bin -f "public/assets/Knobbed Whelk GLTF/scene.bin"
          wrangler r2 object put biotope-assets/knobbed-whelk-material_0_baseColor.jpeg -f "public/assets/Knobbed Whelk GLTF/textures/material_0_baseColor.jpeg"
          wrangler r2 object put biotope-assets/potted-plant-1-01_-_Default_0_baseColor.png -f "public/assets/Potted Plant 1/textures/01_-_Default_0_baseColor.png"
          wrangler r2 object put biotope-assets/potted-plant-1-01_-_Default_baseColor.png -f "public/assets/Potted Plant 1/textures/01_-_Default_baseColor.png"
          wrangler r2 object put biotope-assets/smoked-fish-raw-T_weflciqaa_8K_B.png -f "public/assets/Smoked Fish Raw/Textures/T_weflciqaa_8K_B.png"
          wrangler r2 object put biotope-assets/smoked-fish-raw-T_weflciqaa_8K_N.png -f "public/assets/Smoked Fish Raw/Textures/T_weflciqaa_8K_N.png"
          wrangler r2 object put biotope-assets/smoked-fish-raw-T_weflciqaa_8K_ORM.png -f "public/assets/Smoked Fish Raw/Textures/T_weflciqaa_8K_ORM.png"
          wrangler r2 object put biotope-assets/ai-dried-bay-leaves.png -f "public/assets/AI Dried Bay Leaves.png"
