name: Upload Assets to Cloudflare R2

on:
  push:
    branches: [main]

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      BUCKET_NAME: ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}
    steps:
      - uses: actions/checkout@v3

      - name: Create wrangler.toml dynamically
        run: |
          cat <<EOF > wrangler.toml
          name = "biotope-uploader"
          account_id = "${CLOUDFLARE_ACCOUNT_ID}"
          compatibility_date = "2025-07-03"

          [[r2_buckets]]
          binding = "R2_BUCKET"
          bucket_name = "${BUCKET_NAME}"
          EOF

      - name: Install Cloudflare Wrangler
        run: npm install -g wrangler

      - name: Check Wrangler Authentication
        run: wrangler whoami

      - name: Upload files to R2
        run: |
          wrangler r2 object put ${BUCKET_NAME}/weflciqaa_tier_0.gltf -f "public/assets/Smoked Fish Raw/weflciqaa_tier_0.gltf" --remote
          wrangler r2 object put ${BUCKET_NAME}/weflciqaa_tier_0.bin -f "public/assets/Smoked Fish Raw/weflciqaa_tier_0.bin" --remote
          wrangler r2 object put ${BUCKET_NAME}/potted-plant-1-scene.gltf -f "public/assets/Potted Plant 1/scene.gltf" --remote
          wrangler r2 object put ${BUCKET_NAME}/potted-plant-1-scene.bin -f "public/assets/Potted Plant 1/scene.bin" --remote
          # Knobbed Whelk関連のアセットアップロードは削除されました
          wrangler r2 object put ${BUCKET_NAME}/potted-plant-1-01_-_Default_0_baseColor.png -f "public/assets/Potted Plant 1/textures/01_-_Default_0_baseColor.png" --remote
          wrangler r2 object put ${BUCKET_NAME}/potted-plant-1-01_-_Default_baseColor.png -f "public/assets/Potted Plant 1/textures/01_-_Default_baseColor.png" --remote
          wrangler r2 object put ${BUCKET_NAME}/smoked-fish-raw-T_weflciqaa_8K_B.png -f "public/assets/Smoked Fish Raw/Textures/T_weflciqaa_8K_B.png" --remote
          wrangler r2 object put ${BUCKET_NAME}/smoked-fish-raw-T_weflciqaa_8K_N.png -f "public/assets/Smoked Fish Raw/Textures/T_weflciqaa_8K_N.png" --remote
          wrangler r2 object put ${BUCKET_NAME}/smoked-fish-raw-T_weflciqaa_8K_ORM.png -f "public/assets/Smoked Fish Raw/Textures/T_weflciqaa_8K_ORM.png" --remote
          wrangler r2 object put ${BUCKET_NAME}/ai-dried-bay-leaves.png -f "public/assets/AI Dried Bay Leaves.png" --remote
